version: "2.0"
services:
  clinical-db:
    image: neo4j:latest
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - ~/neo4j/data:/data
      - ~/neo4j/plugins:/plugins
      - ~/neo4j/logs:/logs
      - ~/neo4j/import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/ZXm#uURg!*3D7yDYvX$$6
      - NEO4JLABS_PLUGINS=["n10s"]
    restart: unless-stopped

  clinical-api:
    build:
      context: .
    environment:
      - NEO4J_PASS
      - AUTH0_AUDIENCE
      - AUTH0_CLIENT_SECRET
      - AUTH0_CLAIMS
      - AUTH0_DOMAIN
    ports:
      - 4001:4001
      - 9229:9229
    depends_on:
      - clinical-db
    restart: unless-stopped
